In [1]:
#deploys pattern recognition to identify and quantify relationship between different yet related items
#used for product recommendations to generate business value

#na = number of times A appeared, nb = number of times B appeared, 
#nab = number of times A and B appeared together, n = total number of observations
#support(A) = na/n
#support(A->B) = nab/na
#confidence(A -> B) = support(A->B)/support(A) #how likely B is purchased given that A was purchased
#lift(A->B) = confidence(A->B)/support(B)
#lift score > 1: if A is purchased, it is likely that B will also be purchased
#lift score < 1: if A is purchased, it is unlikely that B will also be purchased
#lift sore = 1: there is no association between A and B

In [2]:
#association rule mining using apriori algorithm

In [6]:
%pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting mlxtend
  Downloading mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: scipy>=1.16.3 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.18.1)
Requirement already satisfied: numpy>=2.3.5 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (2.5.3)
Requirement already satisfied: pandas>=2.3.3 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (3.0.5)
Requirement already satisfied: scikit-learn>=1.8.0 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (3.11.1)
Requirement already satisfied: joblib>=1.5.2 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.6.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from joblib>=1.5.2->mlxtend) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from pandas>=2.3.3->mlxtend) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\despi\AppData\Roaming\Python\Python314\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 1.4/1.4 MB 14.0 MB/s  0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.25.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [8]:
data = pd.read_csv(r"C:\Users\despi\OneDrive\Desktop\Python for DS and ML Part 2\data\groceries.csv")

In [9]:
data.head()

,1,2,3,4,5,6,7,8,9
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN

In [10]:
basket_sets = data.stack().str.get_dummies().groupby(level=0).sum()

In [11]:
basket_sets.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [12]:
basket_sets_bool = basket_sets.astype(bool)
apriori(basket_sets_bool, min_support = 0.02)

      support                    itemsets
0    0.028155              frozenset({1})
1    0.054369              frozenset({8})
2    0.032039              frozenset({9})
3    0.027508             frozenset({10})
4    0.072492             frozenset({11})
..        ...                         ...
105  0.022977       frozenset({154, 163})
106  0.033981       frozenset({162, 158})
107  0.055987       frozenset({162, 163})
108  0.022977  frozenset({121, 162, 101})
109  0.022977  frozenset({162, 163, 101})

[110 rows x 2 columns]

In [13]:
basket_sets_bool = basket_sets.astype(bool)
apriori(basket_sets_bool, min_support = 0.02, use_colnames=True)

      support                                           itemsets
0    0.028155                              frozenset({UHT-milk})
1    0.054369                                  frozenset({beef})
2    0.032039                               frozenset({berries})
3    0.027508                             frozenset({beverages})
4    0.072492                          frozenset({bottled beer})
..        ...                                                ...
105  0.022977                frozenset({tropical fruit, yogurt})
106  0.033981        frozenset({whole milk, whipped/sour cream})
107  0.055987                    frozenset({whole milk, yogurt})
108  0.022977  frozenset({other vegetables, root vegetables, ...
109  0.022977  frozenset({other vegetables, whole milk, yogurt})

[110 rows x 2 columns]

In [15]:
df_combo = basket_sets.astype(bool)

frequent_itemsets = apriori(df_combo, min_support = 0.002, use_colnames=True)

frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

frequent_itemsets

       support                                           itemsets  length
0     0.007120                 frozenset({Instant food products})       1
1     0.028155                              frozenset({UHT-milk})       1
2     0.002913                      frozenset({abrasive cleaner})       1
3     0.003560                      frozenset({artif. sweetener})       1
4     0.014887                         frozenset({baking powder})       1
...        ...                                                ...     ...
2313  0.002265  frozenset({other vegetables, root vegetables, ...       5
2314  0.002589  frozenset({other vegetables, citrus fruit, who...       5
2315  0.002265  frozenset({other vegetables, pip fruit, whole ...       5
2316  0.002265  frozenset({other vegetables, root vegetables, ...       5
2317  0.002265  frozenset({other vegetables, tropical fruit, w...       5

[2318 rows x 3 columns]

In [17]:
frequent_itemsets[(frequent_itemsets['length'] >= 3)]

       support                                           itemsets  length
1260  0.002589  frozenset({other vegetables, bottled water, UH...       3
1261  0.002265         frozenset({bottled water, UHT-milk, soda})       3
1262  0.002589  frozenset({other vegetables, whole milk, bakin...       3
1263  0.002265  frozenset({baking powder, whole milk, whipped/...       3
1264  0.002589             frozenset({beef, whole milk, berries})       3
...        ...                                                ...     ...
2313  0.002265  frozenset({other vegetables, root vegetables, ...       5
2314  0.002589  frozenset({other vegetables, citrus fruit, who...       5
2315  0.002265  frozenset({other vegetables, pip fruit, whole ...       5
2316  0.002265  frozenset({other vegetables, root vegetables, ...       5
2317  0.002265  frozenset({other vegetables, tropical fruit, w...       5

[1058 rows x 3 columns]

In [19]:
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold = 0.9)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,"frozenset({curd, hamburger meat})",frozenset({whole milk}),0.003236,0.256634,0.003236,1.000000,3.896595,1.0,0.002406,inf,0.745779,0.012610,1.000000,0.506305
1,"frozenset({frozen fish, root vegetables})",frozenset({whole milk}),0.002265,0.256634,0.002265,1.000000,3.896595,1.0,0.001684,inf,0.745054,0.008827,1.000000,0.504414
2,"frozenset({bottled water, sausage, yogurt})",frozenset({soda}),0.003560,0.159223,0.003236,0.909091,5.709534,1.0,0.002669,9.248544,0.827801,0.020284,0.891875,0.464708
3,"frozenset({bottled water, sausage, soda})",frozenset({yogurt}),0.003560,0.136893,0.003236,0.909091,6.640877,1.0,0.002749,9.494175,0.852452,0.023585,0.894672,0.466366
4,"frozenset({pip fruit, whole milk, butter})",frozenset({other vegetables}),0.003560,0.192557,0.003236,0.909091,4.721161,1.0,0.002551,8.881877,0.791004,0.016779,0.887411,0.462949

In [20]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold = 1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({other vegetables}),frozenset({Instant food products}),0.192557,0.007120,0.002265,0.011765,1.652406,1.0,0.000894,1.004700,0.488978,0.011475,0.004678,0.164973
1,frozenset({Instant food products}),frozenset({other vegetables}),0.007120,0.192557,0.002265,0.318182,1.652406,1.0,0.000894,1.184250,0.397653,0.011475,0.155584,0.164973
2,frozenset({root vegetables}),frozenset({Instant food products}),0.110032,0.007120,0.002265,0.020588,2.891711,1.0,0.001482,1.013752,0.735065,0.019718,0.013565,0.169385
3,frozenset({Instant food products}),frozenset({root vegetables}),0.007120,0.110032,0.002265,0.318182,2.891711,1.0,0.001482,1.305286,0.658875,0.019718,0.233884,0.169385
4,frozenset({bottled water}),frozenset({UHT-milk}),0.111974,0.028155,0.006472,0.057803,2.053020,1.0,0.003320,1.031467,0.577587,0.048426,0.030507,0.143844

In [24]:
rules[(rules['lift']>=5) & (rules['confidence']>=0.8)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
7110,"frozenset({bottled water, sausage, yogurt})",frozenset({soda}),0.003560,0.159223,0.003236,0.909091,5.709534,1.0,0.002669,9.248544,0.827801,0.020284,0.891875,0.464708
7111,"frozenset({bottled water, sausage, soda})",frozenset({yogurt}),0.003560,0.136893,0.003236,0.909091,6.640877,1.0,0.002749,9.494175,0.852452,0.023585,0.894672,0.466366
7378,"frozenset({sausage, canned beer, rolls/buns})",frozenset({shopping bags}),0.002589,0.082848,0.002265,0.875000,10.561523,1.0,0.002051,7.337217,0.907667,0.027237,0.863709,0.451172
8132,"frozenset({dessert, other vegetables, whipped/...",frozenset({yogurt}),0.002913,0.136893,0.002589,0.888889,6.493302,1.0,0.002190,7.767961,0.848466,0.018868,0.871266,0.453901
8186,"frozenset({other vegetables, pastry, frankfurt...",frozenset({rolls/buns}),0.002265,0.194498,0.002265,1.000000,5.141431,1.0,0.001825,inf,0.807331,0.011647,1.000000,0.505824
8315,"frozenset({whole milk, pork, hamburger meat})",frozenset({other vegetables}),0.002589,0.192557,0.002589,1.000000,5.193277,1.0,0.002090,inf,0.809539,0.013445,1.000000,0.506723